# Generated by Django 2.1.4 on 2018-12-05 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MaintainWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('order', models.SmallIntegerField(default=1)),
                ('task_type', models.CharField(choices=[('sshtask', 'Run Shell Script'), ('scptask', 'SSH File Transfer')], max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'failed'), (1, 'success'), (2, 'error'), (3, 'running')])),
                ('errors', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bernard.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='SCPTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_path', models.CharField(max_length=128)),
                ('remote_path', models.CharField(max_length=128)),
                ('bind_hosts', models.ManyToManyField(blank=True, to='MaintainWeb.BindHosts')),
                ('host_groups', models.ManyToManyField(blank=True, to='MaintainWeb.HostGroups')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bernard.Job')),
            ],
        ),
        migrations.CreateModel(
            name='SSHTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commands', models.TextField(verbose_name='ssh commands')),
                ('bind_hosts', models.ManyToManyField(blank=True, to='MaintainWeb.BindHosts')),
                ('host_groups', models.ManyToManyField(blank=True, to='MaintainWeb.HostGroups')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bernard.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default plan', max_length=64)),
                ('order', models.SmallIntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bernard.Plan')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bernard.Stage'),
        ),
    ]
